function Turb = import_T_SIMCOSTA(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SIMCOSTARS1OCEAN2016031120220605 = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  SIMCOSTARS1OCEAN2016031120220605 = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Turbidity = importfile("/Turbidity_SIMCOSTA/SIMCOSTA_RS-1_OCEAN_2016-03-11_2022-06-05.csv", [30, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Dec-2022 11:03:30

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [30, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["YEAR", "MONTH", "DAY", "HOUR", "MINUTE", "SECOND", "Avg_Turb"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Turb = readtable(filename, opts);

end
